development:
  adapter: postgresql
  database: needly_development
  host: localhost
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: needly_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: needly_production
  pool: 5
  timeout: 5000